print ('What do you get when you cross a snowman with a vampire?')
input()
print('frostbite')
print()
print('What do dentists call an astronaut\'s cavity?')
input()
print('A black Hole')
print()
print('Knock knock.')
input()
print("Who's there?")
input()
print('interupting cow.')
input()
print('Interupting cow wh ' , end= '')
print('-Moo!')
